#!/bin/bash -e

# This should prevent this script to load the local git user config:
# (HOME overwrite)
HOME=../../../git-config

git init

# Create binary
echo -e 'abc \x0 def' > binary
git add binary

# Create image
echo -e 'abc \x0 def' > image.jpg
git add image.jpg

# Create too large file
yes | head -n 102400 > toolarge
git add toolarge

git commit -am first
