#!/bin/bash -e

# This should prevent this script to load the local git user config: 
# (HOME overwrite)
HOME=../../../git-config

git init

echo 1 > test
echo -n 2 >> test
git add test
git commit -m old

echo 1 > test
echo 2 >> test
git add test
git commit -m new
