#!/bin/bash -e
git init

echo "int a;" > test.c
echo "function test() {}" > test.js
git add test.c
git add test.js
git commit --no-gpg-sign -m "Add some code"

git commit --no-gpg-sign --allow-empty -m "Empty commit 1"
git tag tag1

git commit --no-gpg-sign --allow-empty -m "Empty commit 2"
